### ISSUE TITLE
[feat] FusedLinearCrossEntropy support for Mistral

### ISSUE THREAD

**Issue by yundai424** [linkedin/Liger-Kernel#100]
### 🚀 The feature, motivation and pitch

1) add monkey patch availability, 2) update convergence test accordingly

**Comment by llllvvuu** [comment]
I think

> ```
> [rank1]: Traceback (most recent call last):
> [rank1]:   File "/workspace/train/run_clm.py", line 810, in <module>
> [rank1]:     main()
> [rank1]:   File "/workspace/train/run_clm.py", line 747, in main
> [rank1]:     train_result = trainer.train(resume_from_checkpoint=checkpoint)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
> [rank1]:     return inner_training_loop(
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
> [rank1]:     tr_loss_step = self.training_step(model, inputs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3318, in training_step
> [rank1]:     loss = self.compute_loss(model, inputs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3363, in compute_loss
> [rank1]:     outputs = model(**inputs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
> [rank1]:     return self._call_impl(*args, **kwargs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
> [rank1]:     return forward_call(*args, **kwargs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1593, in forward
> [rank1]:     else self._run_ddp_forward(*inputs, **kwargs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1411, in _run_ddp_forward
> [rank1]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
> [rank1]:     return self._call_impl(*args, **kwargs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
> [rank1]:     return forward_call(*args, **kwargs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
> [rank1]:     return model_forward(*args, **kwargs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
> [rank1]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
> [rank1]:     return func(*args, **kwargs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/liger_kernel/transformers/model/mistral.py", line 110, in lce_forward
> [rank1]:     loss = lce(self.lm_head.weight, shift_hidden_states, shift_labels)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
> [rank1]:     return self._call_impl(*args, **kwargs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
> [rank1]:     return forward_call(*args, **kwargs)
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/liger_kernel/transformers/fused_linear_cross_entropy.py", line 13, in forward
> [rank1]:     return LigerFusedLinearCrossEntropyFunction.apply(
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
> [rank1]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
> [rank1]:   File "/opt/conda/lib/python3.10/site-packages/liger_kernel/ops/fused_linear_cross_entropy.py", line 113, in forward
> [rank1]:     torch.addmm(
> [rank1]: RuntimeError: mat1 and mat2 must have the same dtype, but got BFloat16 and Float
> ```
> 
> Error on Mistral DDP bf16 mixed precision trainning. Hugging Face Trainer. liger-kernel-nightly.
> 
> https://github.com/linkedin/Liger-Kernel/blob/aa1a2a9166d426d656cd37dd6c11db878816c59a/src/liger_kernel/ops/fused_linear_cross_entropy.py#L103
> 
> `logits_chunk` cast to `BFloat16` here. What's the most straightforward solution?

I think this is not unique to Mistral. I ran into this issue with Llama too
