### ISSUE TITLE
Issue Using TRL DPOTrainer with Liger Kernels

### ISSUE THREAD

**Issue by sam-h-bean** [linkedin/Liger-Kernel#113]
### 🐛 Describe the bug

The concatenated forward in the standard `DPOTrainer` in TRL does not work with Liger Kernels. This is because the concatenated forward call in this function seen [here](https://github.com/huggingface/trl/blob/main/trl/trainer/dpo_trainer.py#L1306-L1311) does not supply the labels field. This leads to the following error:

```bash
liger_kernel/transformers/model/llama.py", line 102, in lce_forward
    shift_labels = labels[..., 1:].contiguous()
TypeError: 'NoneType' object is not subscriptable
```

### Reproduce

Take the standard [DPO script in TRL](https://github.com/huggingface/trl/blob/main/examples/scripts/dpo.py) and set the model_id to `meta-llama/Meta-Llama-3.1-8B-Instruct` or something. Next apply the Liger kernel monkey patch and run the script. It will crash for the labels being `None` in the `concatenated_forward` call.

### Versions

Liger stable

**Comment by yundai424** [comment]
Hi @sam-h-bean thanks for reporting the issue! For llama model we by default enable `lm_head` fusion with cross entropy loss by replacing the whole `LlamaModelForCausalLM.forward`, with implicit assumption that label will be provided. For a quick workaround you can set `apply_liger_kernel_to_llama(fused_linear_cross_entropy=False, cross_entropy=True)` to disable the fusion but still benefit from acceleration on other ops (CE itself, etc.)

An action item on liger code base: fall back to torch native forward in `lce_forward` when label is not provided. @ByronHsu fyi
