### ISSUE TITLE
[feat] Is Qwen1.5 supported?

### ISSUE THREAD

**Issue by YingchaoX** [linkedin/Liger-Kernel#133]
### 🚀 The feature, motivation and pitch

I am currently using qwen1.5-14b, and I'm not sure if the templates for qwen2 are compatible with qwen1.5.

**Comment by ByronHsu** [comment]
cc @chiwanpark

**Comment by chiwanpark** [comment]
@YingchaoX cc @ByronHsu 
AFAIK, You can apply Liger patches to Qwen1.5 because Qwen1.5 shares the architecture with Qwen2 ([config](https://huggingface.co/Qwen/Qwen1.5-14B/blob/main/config.json#L3)). But, I didn't test it yet.

**Comment by ByronHsu** [comment]
i believe it should work
