### ISSUE TITLE
[feat] functional API for the ops

### ISSUE THREAD

**Issue by yundai424** [linkedin/Liger-Kernel#151]
### 🚀 The feature, motivation and pitch

Right now for many ops we only provide the torch autograd `Function` class impl. It might be more convenient if people can do  `liger_swiglu(a, b)` instead of `LigerSiLUMulFunction.apply(a, b)` by defining `liger_swiglu(a, b) = LigerSiLUMulFunction.apply(a, b)` in `ops/`

**Comment by ByronHsu** [comment]
cc @tyler-romero

**Comment by ByronHsu** [comment]
the api can be like `liger_kernel.transformers.functional`, inspired from https://pytorch.org/docs/stable/nn.functional.html

**Comment by S1ro1** [comment]
#take @yundai424
