### ISSUE TITLE
test_fused_linear_cross_entropy: @pytest.mark.parametrize("bias", [True, False]) test_correctness is failing on CI

### ISSUE THREAD

**Issue by helloworld1** [linkedin/Liger-Kernel#160]
### 🐛 Describe the bug

test_fused_linear_cross_entropy: @pytest.mark.parametrize("bias", [True, False]) test_correctness is failing on CI
https://github.com/linkedin/Liger-Kernel/actions/runs/10609021368/job/29404257304

The code works fine on A100 but not on AMD 7900 and GTX3900

### Versions

git latest

**Comment by ByronHsu** [comment]
cc @davidgonmar. likely the tol is too tight

**Comment by davidgonmar** [comment]
I tested on L4/L40 and worked fine. I don"t have access to AMD cards (or a 3090) to test it, but feel free to change the tolerance to something that works if it is that (it seems, since fp32 is fine)

**Comment by shimizust** [comment]
Tolerances were updated, tests are passing
