### ISSUE TITLE
[testing bug] Many convergence tests are incorrect - comparing LigerKernel against itself

### ISSUE THREAD

**Issue by tyler-romero** [linkedin/Liger-Kernel#176]
### 🐛 Describe the bug

We typically test each model twice, once with float32 and once afterwards with bfloat16. The second test for a given model never reverts the monkeypatch of the first, so they are comparing LigerKernel against itself.

A fix would look like a reverse monkeypatch.

### Versions

python -m liger_kernel.env_report                                                           
Environment Report:
-------------------
Operating System: Linux-6.5.0-44-generic-x86_64-with-glibc2.35
Python version: 3.10.13
PyTorch version: 2.4.0+cu121
CUDA version: 12.1
Triton version: 3.0.0
Transformers version: 4.45.0.dev0

**Comment by ByronHsu** [comment]
critical bug catch!!

**Comment by austin362667** [comment]
#take

**Comment by austin362667** [comment]
Great catch on the bug! Thank you so much. I’ve drafted [PR #232](https://github.com/linkedin/Liger-Kernel/pull/232) to address this issue. However, if it resolves the problem, it may potentially introduce other value mismatch issues. We can fix them in follow-up PRs.
