### ISSUE TITLE
Division by zero when total_n_ignore = 0

### ISSUE THREAD

**Issue by 44670** [linkedin/Liger-Kernel#177]
### 🐛 Describe the bug

When the input sample does not contain non-ignore labels, a division-by-zero error will be raised.

[rank1]:   File "/data/conda3/lib/python3.11/site-packages/liger_kernel/ops/fused_linear_cross_entropy.py", line 114, in forward
[rank1]:     n_non_ignore / total_n_non_ignore
[rank1]:     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
[rank1]: ZeroDivisionError: division by zero

### Versions

latest

**Comment by ByronHsu** [comment]
cc @shivam15s can fix this in the refactoring change

**Comment by ByronHsu** [comment]
The issue is fixed
