### ISSUE TITLE
[SFTTrainer] Add doc in huggingface sfttrainer website

### ISSUE THREAD

**Issue by ByronHsu** [linkedin/Liger-Kernel#184]
### 🚀 The feature, motivation and pitch

add liger kernel usage at https://huggingface.co/docs/trl/en/sft_trainer

**Comment by ryankert01** [comment]
#take @ByronHsu , I would like to help on this one.

**Comment by ByronHsu** [comment]
awesomeee!

**Comment by ByronHsu** [comment]
@ryankert01 any progress?

**Comment by ryankert01** [comment]
@ByronHsu Currently trying to write the example and verify it!
