### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by merryHunter** [linkedin/Liger-Kernel#204]
Hi,

Current README section on API for kernels has deprecated (below is just one of examples):

It should become:  
`from liger_kernel.transformers.**fused_linear_cross_entropy** import LigerFusedLinearCrossEntropyLoss`

It's sort of easy fix, let me know if you welcome PR on that!

PS: btw the tool is great, quickly tested RMSNorm for litgpt, works definitely faster!

### Reproduce

```
>>> from liger_kernel.transformers import LigerFusedLinearCrossEntropyLoss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'LigerFusedLinearCrossEntropyLoss' from 'liger_kernel.transformers' (/opt/conda/lib/python3.10/site-packages/liger_kernel/transformers/__init__.py)
```

### Versions

Environment Report:
-------------------
Operating System: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python version: 3.10.13
PyTorch version: 2.5.0.dev20240825+cu121
CUDA version: 12.1
Triton version: 3.0.0
Transformers version: 4.44.2

**Comment by ByronHsu** [comment]
Awesome! Please send a PR!

**Comment by ByronHsu** [comment]
btw we are looking for contributor at https://github.com/linkedin/Liger-Kernel/issues/139. Would you be interested in sending rmsnorm integration PR to litgpt? others can come later

**Comment by merryHunter** [comment]
I might be, will take a look tomorrow to see what's needed to create a PR there and start a conversation

**Comment by ByronHsu** [comment]
this issue will be resolved at https://github.com/linkedin/Liger-Kernel/issues/205.
