### ISSUE TITLE
Uplift kernel api to top level

### ISSUE THREAD

**Issue by ByronHsu** [linkedin/Liger-Kernel#205]
### 🐛 Describe the bug

Currently on the doc, it is 
<img width="828" alt="image" src="https://github.com/user-attachments/assets/b0a80e97-4834-449c-b532-ca0bfa43fd9c">

However, the single kernel is actually hidden inside python file. We should uplift it to the top level to make sure users can import them just like the above

### Versions

na

**Comment by ByronHsu** [comment]
Related issue: https://github.com/linkedin/Liger-Kernel/issues/204

**Comment by ryankert01** [comment]
#take @ByronHsu
