### ISSUE TITLE
AutoLigerKernelForCausalLM.from_pretrained discards hub_kwargs_names

### ISSUE THREAD

**Issue by uris-opti** [linkedin/Liger-Kernel#250]
### 🐛 Describe the bug

AutoLigerKernelForCausalLM.from_pretrained retain only the keyword args present in the model configuration, which do not include hub_kwargs_names -> [
            "cache_dir",
            "force_download",
            "local_files_only",
            "proxies",
            "resume_download",
            "revision",
            "subfolder",
            "use_auth_token",
            "token",
        ]
therefore cannot replace AutoModelForCausalLM

### Reproduce

N/A

### Versions

N/A

**Comment by tyler-romero** [comment]
+1, I notice that some models don't have `attn_implementation` in their config even though its a valid keyword arg to `AutoModelForCausalLM` - so the user-specified `attn_implementation` gets discarded as well.

**Comment by shimizust** [comment]
Thanks for reporting! Currently we are only keeping kwargs that are present in the model config. I wasn't aware of this other set of valid args--let me look into it

**Comment by uris-opti** [comment]
Thanks for looking into it!
I don't know what's the motivation for filtering the kwargs, but I would consider removing this logic completely,
After seeing Tyler's comment, I looked around the transformers code and noticed there are many many kwargs that are not in the config and they vary between from_pretrained implementations, 
I also saw that each from_pretrained implementation handles extra kwargs, so just passing on the kwargs seems safe
🙏

**Comment by shimizust** [comment]
Hm, when I tried not removing extra kwargs (e.g. those that get passed to the liger monkey patch function) it resulted in errors, hence the filtering. Looking at this now

**Comment by shimizust** [comment]
If you can take a look @yundai424 @JasonZhu1313
