### ISSUE TITLE
test.utils.assert_verbose_allclose has multiple bugs

### ISSUE THREAD

**Issue by Tcc0403** [linkedin/Liger-Kernel#259]
### 🐛 Describe the bug

False when diff is nan
https://github.com/linkedin/Liger-Kernel/blob/ce71d59b0b0894f9f3e7512f5a3bf3780c5a1499/test/utils.py#L59
condition is False when num_mismatched is 1.
https://github.com/linkedin/Liger-Kernel/blob/ce71d59b0b0894f9f3e7512f5a3bf3780c5a1499/test/utils.py#L71

I found these bugs when tweaking current test files. Some implementations might be wrong if those tests are relied on this function.

For example, KLDiv can't pass the unit test if we simply replace `assert_verbose_allclose` with `assert torch.allclose()`

### Versions

```
❯ python -m liger_kernel.env_report
Environment Report:
-------------------
Operating System: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python version: 3.10.12
PyTorch version: 2.4.0+cu121
CUDA version: 12.1
Triton version: 3.0.0
Transformers version: 4.44.2
```

**Comment by yundai424** [comment]
ooops thanks for catching this bug, please feel free to draft a PR! Is KLDiv the only test failing or there are some others too?

**Comment by Tcc0403** [comment]
I haven't tried others. I'll just make a pr to test them.

**Comment by Tcc0403** [comment]
> ooops thanks for catching this bug, please feel free to draft a PR! Is KLDiv the only test failing or there are some others too?

@yundai424 only KLDiv it seems

**Comment by S1ro1** [comment]
@Tcc0403 Can you please check if #262 fixes the issue?
