### ISSUE TITLE
Weights are not copied when model is already instantiated

### ISSUE THREAD

**Issue by ByronHsu** [linkedin/Liger-Kernel#279]
### 🐛 Describe the bug

In https://github.com/linkedin/Liger-Kernel/pull/199, we introduced an api to replace the already instantiated nn.module with liger module. However, the weights are not copied over, so it causes issue https://github.com/linkedin/Liger-Kernel/issues/268 and https://github.com/linkedin/Liger-Kernel/issues/257. 

Solutions
1. only patch with the forward function of liger module
2. if patching globally with the forward function of liger module, do we still need the post-init patching? 

### Versions

na

**Comment by shimizust** [comment]
Thanks for finding the issue and suggesting a solution @ByronHsu . Here is the fix (waiting on other fixes to make all the convergence tests pass): https://github.com/linkedin/Liger-Kernel/pull/280

We still need post-init patching--patching the forward method globally won't replace the forward method of the modules on the already instantiated model.
