### ISSUE TITLE
OOM issue occurs when training Llama-3-8B

### ISSUE THREAD

**Issue by dongwook92** [linkedin/Liger-Kernel#311]
### 🐛 Describe the bug

Hello, I used to primarily use unsloth, but I was intrigued by the potential of liger-kernel, so I'm currently testing it.

However, after modifying `examples/huggingface/run_llama.sh` as shown below to test in my environment, I encountered an OOM error. (max_seq_len: 512, batch_size: 2, A100(40GB))

I suspect the issue might be that the kernel replacement did not occur properly, but I'm not sure why this problem is happening. 

### Reproduce

run `examples/huggingface/run_llama.sh` with following modifications.

```run_llama.sh
python training.py \
    --bf16 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --eval_strategy "no" \
    --save_strategy "no" \
    --learning_rate 6e-6 \
    --weight_decay 0.05 \
    --warmup_ratio 0.1 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --include_num_input_tokens_seen \
    --report_to none \
    --seed 42 \
    --use_liger True \
    --output_dir alpaca_finetuning
```

### Versions

  GPU: A100(40GB)
  nvidia driver version: 535.54.03
  cuda version: 12.4
  
  Environment Report:
  Operating System: Linux-4.18.0-305.el8.x86_64-x86_64-with-glibc2.35
  Python version: 3.11.10
  PyTorch version: 2.4.1+cu124
  CUDA version: 12.4
  Triton version: 3.0.0
  Transformers version: 4.45.2

**Comment by ByronHsu** [comment]
Might be because we are running on A100 (80GB)

**Comment by dongwook92** [comment]
I see. Thank you for your response. 

By any chance, does the effect of memory reduction and speed improvement through liger-kernel appear more significantly when using multiple GPUs compared to a single GPU?
