### ISSUE TITLE
Liger kernel does not speed up, and even slow down in many scenarios

### ISSUE THREAD

**Issue by fzyzcjy** [linkedin/Liger-Kernel#323]
### 🐛 Describe the bug

Hi thanks for the library! When testing it, I find it use much less memory (which is very great!). However, it seems that it is sometimes much slower than not using it. 

Details that may be helpful:
* seq length is ~2000
* not using packing, thus seq length is dynamic, such as 1789, 1987, 2012, ... (I tried to pad to multiple of 8 but no use)
* batch size = 1 or 2 or 4(to avoid OOM), and realize smaller batch sizes are even much slower
* RTX4090 GPU, llama 3.2 1B or qwen 2.5 1.5B or qwen 2.5 0.5B, full fine-tuning

### Versions

```
Environment Report:
-------------------
Operating System: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
Python version: 3.11.7
PyTorch version: 2.4.0+cu121
CUDA version: 12.1
Triton version: 3.0.0
Transformers version: 4.45.2
```

**Comment by ByronHsu** [comment]
this is expected since when batch size is small, the program enters [cpu overhead bound](https://horace.io/brrr_intro.html) mode. liger kernel is more helpful in the compute or bandwidth bound scenerios.

**Comment by fzyzcjy** [comment]
@ByronHsu Thank you! I wonder whether there are ways to avoid this. For example, I guess torch.compile (https://github.com/linkedin/Liger-Kernel/issues/174) will help to reduce cpu overhead?

**Comment by ByronHsu** [comment]
replied in https://github.com/linkedin/Liger-Kernel/issues/174#issuecomment-2439047335
