### ISSUE TITLE
A more general way to get the base model

### ISSUE THREAD

**Issue by why-in-Shanghaitech** [linkedin/Liger-Kernel#337]
### 🚀 The feature, motivation and pitch

It might improve compatibility to access the base models through the `base_model_prefix` attribute.

For example, change these lines
https://github.com/linkedin/Liger-Kernel/blob/659d7d7856bf755c1cf26f2df6173da68841ba17/src/liger_kernel/transformers/monkey_patch.py#L111-L119

into
```python
base_model = getattr(model, model.base_model_prefix, model)
```

I'm willing to add a PR if you feel like this is a good idea.

### Alternatives

The current implementation is working.

### Additional context

I am working on a variant of liger kernel and the code works in my context. I have not tested on models other than `llama` yet.

Huggingface `transformers` access the base models in this way:

https://github.com/huggingface/transformers/blob/b53e44e847230a39caecc320527776ed80a3ceff/src/transformers/generation/utils.py#L437-L445accesses

**Comment by ByronHsu** [comment]
sounds reasonable to me. i believe this can work beyond llama
