### ISSUE TITLE
Keyword arguments for liger functional

### ISSUE THREAD

**Issue by Tcc0403** [linkedin/Liger-Kernel#368]
### 🚀 The feature, motivation and pitch

Liger's functional doesn't support keyword arguments because it's implemented by replacing `torchautograd.Function.apply`.

kwargs support is necessary for LigerCrossEntropyLoss to patch transformers model after GA fix 
https://github.com/huggingface/transformers/blob/a06a0d12636756352494b99b5b264ac9955bc735/src/transformers/models/llama/modeling_llama.py#L1224

**Comment by ByronHsu** [comment]
CE is fixed by https://github.com/linkedin/Liger-Kernel/pull/375. But need to add functional wrapper for other modules

**Comment by hongpeng-guo** [comment]
I can take this one 😄
