### ISSUE TITLE
Is eager attention still required for Gemma2?

### ISSUE THREAD

**Issue by dachenlian** [linkedin/Liger-Kernel#398]
https://github.com/linkedin/Liger-Kernel/blob/81d98ea895255a44a0c787c7afa0ab7c34e32884/src/liger_kernel/transformers/model/gemma2.py#L61

Is this warning related to FlashAttention being previously unable to support Gemma2's softcapping? If so, it was fixed in [v2.6](https://github.com/Dao-AILab/flash-attention#26-softcapping).

**Comment by ByronHsu** [comment]
I copy pasted [gemma2 forward code](https://github.com/huggingface/transformers/blob/052e652d6d53c2b26ffde87e039b723949a53493/src/transformers/models/gemma2/modeling_gemma2.py#L1038) and monkey patched with our FLCE layer. Seems that it was not removed yet. I will update after they make the change.

By the way, I have seen you around when i was in NTU's gym. You lifted massive weight XD

**Comment by dachenlian** [comment]
Small world 😘
It's unfortunate we didn't hang out 🥺
