### ISSUE TITLE
No gradient test in softcap unit test for LigerCrossEntropy

### ISSUE THREAD

**Issue by Tcc0403** [linkedin/Liger-Kernel#418]
### 🐛 Describe the bug

https://github.com/linkedin/Liger-Kernel/blob/7e0f459149d298c84f162363cc6f1347494b80f2/test/transformers/test_cross_entropy.py#L188-L201
There should be a `torch.allclose()` after `backward()`. 

`to.(torch.float32)` in L188 can be moved to L194

### Versions

None

**Comment by austin362667** [comment]
take
