### ISSUE TITLE
[0.5.0] from trl.trainer import ORPOTrainer ModuleNotFoundError: No module named 'trl'

### ISSUE THREAD

**Issue by Fazziekey** [linkedin/Liger-Kernel#458]
### 🐛 Describe the bug

![image](https://github.com/user-attachments/assets/b4e93f25-9b5f-4b67-854b-99f09acadd59)

0.5.0 liger_kernal must rely on trl, however it only install when with dev version

dev = [
    "transformers>=4.44.2",
    "trl>=0.11.0",
    "matplotlib>=3.7.2",
    "flake8>=4.0.1.1",
    "black>=24.4.2",
    "isort>=5.13.2",
    "pytest>=7.1.2",
    "pytest-xdist", 
    "pytest-rerunfailures",
    "datasets>=2.19.2",
    "torchvision>=0.16.2",
    "seaborn",
]

### Reproduce

 pip3 install liger_kernel==0.5.0
from liger_kernel.transformers.rms_norm import LigerRMSNorm

### Versions

0.5.0

**Comment by ByronHsu** [comment]
Apologize. The issue should have been fixed in v0.5.1: https://github.com/linkedin/Liger-Kernel/releases/tag/v0.5.1

**Comment by Fazziekey** [comment]
Thanks
