### ISSUE TITLE
Inquiry about FSDP and PP

### ISSUE THREAD

**Issue by SeungyounShin** [linkedin/Liger-Kernel#67]
Hi,

Thank you for the fantastic work on this project!

I have a few questions regarding the implementation of Fully Sharded Data Parallel (FSDP). Specifically, I'm curious about how FSDP is achieved in your code, as I couldn't find any p2p-related code in the Triton implementation. This leaves me a bit unclear on how pipeline parallelism is facilitated in this context. 

Also, could you let me know if the results of Alpaca(liger kernel + FSDP) have been reproduced correctly?

I’m still new to this, so I might be missing something obvious, and I’d really appreciate any clarification you can provide.

Thank you

**Comment by ByronHsu** [comment]
I believe there is some confusion. We are targeting at the kernel layer, while FSDP/PP is at the distributed layer. The logic of communication is in FSDP/PP source code. 

> could you let me know if the results of Alpaca(liger kernel + FSDP) have been reproduced correctly?

Yes. We use the FSDP integration from Hugging Face with Liger Kernel
